# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Kynf-PZMt0xdlMx3xtObjpbULeMg6zM
"""

import time
from IPython.display import clear_output

def countdown_timer(minutes, seconds):
    total_seconds = minutes * 60 + seconds

    while total_seconds > 0:
        mins, secs = divmod(total_seconds, 60)
        timer = '{:02d}:{:02d}'.format(mins, secs)
        clear_output(wait=True)
        print("Countdown Timer")
        print("----------------")
        print(timer)
        time.sleep(1)
        total_seconds -= 1

    clear_output(wait=True)
    print("Time's up!")

# Example: 1 minute and 30 seconds countdown
countdown_timer(1, 30)